### ISSUE TITLE
KeyError: 'build_type' trying to build NSS with gyp-next >0.12.1

### ISSUE THREAD

**Issue by mozkeeler** [nodejs/gyp-next#182]
```
% ./build.sh --python=python3 --gyp -v
run_scanbuild gyp -f ninja --depth=/Users/dkeeler/src/nss/nss --generator-output=. -Dpython=python3 -Dtarget_arch=arm64 -Denable_sslkeylogfile=1 -Dnss_dist_dir=/Users/dkeeler/src/nss/dist -Dnss_dist_obj_dir=/Users/dkeeler/src/nss/dist/Debug -Dnspr_include_dir=/Users/dkeeler/src/nss/dist/Debug/include/nspr -Dnspr_lib_dir=/Users/dkeeler/src/nss/dist/Debug/lib /Users/dkeeler/src/nss/nss/nss.gyp
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/gyp", line 8, in <module>
    sys.exit(script_main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gyp/__init__.py", line 686, in script_main
    return main(sys.argv[1:])
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gyp/__init__.py", line 678, in main
    return gyp_main(args)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gyp/__init__.py", line 645, in gyp_main
    [generator, flat_list, targets, data] = Load(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gyp/__init__.py", line 111, in Load
    os.path.join(output_dir, "out", default_variables["build_type"]),
KeyError: 'build_type'
```
0.12.1 seems to work fine, but anything after that fails with this error.

**Comment by cclauss** [comment]
These failing line was added in #151.
